/**
 * parse_da_layout.cjs
 * Parses "Lay Out DA new version.xlsx" → src/lib/config/da_layout.ts
 * Run: node scripts/parse_da_layout.cjs
 */
const fs = require('fs');
const path = require('path');
const AdmZip = require ? null : null; // use built-in extraction

const XLSX = path.join(__dirname, '..', 'Lay Out DA new version.xlsx');
const OUT  = path.join(__dirname, '..', 'src', 'lib', 'config', 'da_layout.ts');
const TEMP = process.env.TEMP + '/da_xlsx_extract';

// ---- reuse parsed grid ----
const gridRaw = JSON.parse(fs.readFileSync(process.env.TEMP + '/da_grid.json', 'utf8'));
const rowsByR = {};
for (const row of gridRaw.rows) rowsByR[row.r] = row.cells;

// ---- helpers ----
const isLine  = v => /^LINE\d+/i.test(v);
const isDaMachine = v => /^D\/B\s*#\s*\d+$/i.test(v);
const isSup   = v => v && !isLine(v) && !isDaMachine(v);

// Normalise machine ID: "D/B#41" → "D/B # 041"
function normaliseId(v) {
  const m = v.match(/D\/B\s*#\s*(\d+)/i);
  if (!m) return v;
  return 'D/B # ' + String(parseInt(m[1])).padStart(3, '0');
}

function supColor(v, rgb) {
  if (rgb) return '#' + rgb;
  return '#E0E4E8';
}

// Build a WbCell-like object
// Zone 2 uses explicit column positions for vertical alignment.
// Excel col → CSS grid col: c1→1 (row label), c4→2, c6→3, c8→4...c24→12
// Formula: c=1 → 1; c>=4 → (c-4)/2 + 2
function excelColToGrid(c) {
  if (c === 1) return 1;
  return Math.floor((c - 4) / 2) + 2;
}

const mc  = (v, rgb, col) => ({ kind: 'machine',  v: normaliseId(v), num: parseInt(v.match(/\d+/)[0]), col });
const lc  = v              => ({ kind: 'line',    v });
const sc  = (v, rgb, col)  => ({ kind: 'support', v, color: supColor(v, rgb), col });

function parseRow(r) {
  const cells = (rowsByR[r] || []).filter(c => c.v && c.v !== '').sort((a, b) => a.c - b.c);
  const out = [];
  for (const c of cells) {
    const v = c.v;
    if (isLine(v))           out.push(lc(v));
    else if (isDaMachine(v)) out.push(mc(v, c.rgb));
    else                     out.push(sc(v, c.rgb));
  }
  return out;
}

// Zone 2 rows: preserve Excel column for CSS grid alignment
function parseRowZ2(r) {
  const cells = (rowsByR[r] || []).filter(c => c.v && c.v !== '').sort((a, b) => a.c - b.c);
  const out = [];
  for (const c of cells) {
    const v = c.v; const gridCol = excelColToGrid(c.c);
    if (isDaMachine(v)) out.push(mc(v, c.rgb, gridCol));
    else                out.push(sc(v, c.rgb, gridCol));
  }
  return out;
}

// ---- Zone 1: LINE10-LINE19 ----
const Z1_ROWS = [11, 13, 15, 17, 21, 23, 27, 29, 31, 33, 35];

// ---- Zone 2: LFM row + B/G + Die Bank grid ----
const Z2_ROWS = [39, 45, 47, 49, 51, 53, 55, 57];

const z1rows = Z1_ROWS.map(r => ({ cells: parseRow(r) })).filter(row => row.cells.length > 0);
const z2rows = Z2_ROWS.map(r => ({ cells: parseRowZ2(r), grid: true })).filter(row => row.cells.length > 0);

// Count machines
let totalMachines = 0;
const countMachines = rows => { for (const r of rows) totalMachines += r.cells.filter(c => c.kind === 'machine').length; };
countMachines(z1rows); countMachines(z2rows);
console.log('Zone1 rows:', z1rows.length, '  Zone2 rows:', z2rows.length);
console.log('Total machine positions:', totalMachines);

// ---- emit TypeScript ----
function cellToTs(c) {
  if (c.kind === 'line')    return `{kind:'line',v:${JSON.stringify(c.v)}}`;
  if (c.kind === 'machine') {
    const col = c.col != null ? `,col:${c.col}` : '';
    return `{kind:'machine',v:${JSON.stringify(c.v)},num:${c.num}${col}}`;
  }
  const col = c.col != null ? `,col:${c.col}` : '';
  return `{kind:'support',v:${JSON.stringify(c.v)},color:${JSON.stringify(c.color)}${col}}`;
}
function rowToTs(row, indent='    ') {
  const cells = row.cells.map(cellToTs).join(',');
  const grid = row.grid ? ',grid:true' : '';
  return `${indent}{cells:[${cells}]${grid}}`;
}

const ts = `// AUTO-GENERATED by scripts/parse_da_layout.cjs — do not edit by hand
// Source: "Lay Out DA new version.xlsx"
// Total DA machine positions: ${totalMachines}

export interface DaCell  { kind: 'machine'|'line'|'support'; v: string; num?: number; color?: string; col?: number; }
export interface DaRow   { cells: DaCell[]; grid?: boolean; }
export interface DaZone  { id: string; label: string; supervisor: string; rows: DaRow[]; }

export const DA_FLOOR: DaZone[] = [
  {
    id: 'Z1', label: 'Zone 1', supervisor: '',
    rows: [
${z1rows.map(r => rowToTs(r)).join(',\n')}
    ]
  },
  {
    id: 'Z2', label: 'Zone 2', supervisor: '',
    rows: [
${z2rows.map(r => rowToTs(r)).join(',\n')}
    ]
  },
];
`;

fs.writeFileSync(OUT, ts, 'utf8');
console.log('Written:', OUT);
