// AUTO-GENERATED by scripts/parse_wb_layout.cjs — DO NOT EDIT BY HAND.
// Source: "Lay out wire bond 1.xlsx". Re-run the script to regenerate.

export type WbCellKind = 'machine' | 'line' | 'support';

export interface WbCell {
  kind: WbCellKind;
  v: string;        // displayed text (machine base number, "LINExx", or support label)
  num?: number;     // machine base number (kind === 'machine')
  color?: string;   // support block fill color (kind === 'support')
}

export interface WbRow { cells: WbCell[]; }

export interface WbZone {
  id: string;
  label: string;
  supervisor: string;
  rows: WbRow[];
}

export const WB_FLOOR: WbZone[] = [
  {
    "id": "Z1",
    "label": "ZONE 1",
    "supervisor": "หยก , ย๊ะห์",
    "rows": [
      {
        "cells": [
          {
            "kind": "machine",
            "v": "69",
            "num": 69
          },
          {
            "kind": "machine",
            "v": "50",
            "num": 50
          },
          {
            "kind": "machine",
            "v": "97",
            "num": 97
          },
          {
            "kind": "machine",
            "v": "80",
            "num": 80
          },
          {
            "kind": "machine",
            "v": "62",
            "num": 62
          },
          {
            "kind": "machine",
            "v": "20",
            "num": 20
          },
          {
            "kind": "machine",
            "v": "06",
            "num": 6
          },
          {
            "kind": "machine",
            "v": "25",
            "num": 25
          },
          {
            "kind": "machine",
            "v": "23",
            "num": 23
          },
          {
            "kind": "machine",
            "v": "36",
            "num": 36
          },
          {
            "kind": "machine",
            "v": "63",
            "num": 63
          },
          {
            "kind": "machine",
            "v": "78",
            "num": 78
          },
          {
            "kind": "machine",
            "v": "59",
            "num": 59
          },
          {
            "kind": "machine",
            "v": "26",
            "num": 26
          },
          {
            "kind": "machine",
            "v": "73",
            "num": 73
          },
          {
            "kind": "line",
            "v": "LINE28"
          },
          {
            "kind": "machine",
            "v": "53",
            "num": 53
          },
          {
            "kind": "machine",
            "v": "88",
            "num": 88
          },
          {
            "kind": "machine",
            "v": "90",
            "num": 90
          },
          {
            "kind": "machine",
            "v": "91",
            "num": 91
          },
          {
            "kind": "machine",
            "v": "92",
            "num": 92
          },
          {
            "kind": "machine",
            "v": "93",
            "num": 93
          },
          {
            "kind": "machine",
            "v": "70",
            "num": 70
          },
          {
            "kind": "machine",
            "v": "33",
            "num": 33
          },
          {
            "kind": "machine",
            "v": "61",
            "num": 61
          },
          {
            "kind": "machine",
            "v": "95",
            "num": 95
          },
          {
            "kind": "machine",
            "v": "94",
            "num": 94
          },
          {
            "kind": "machine",
            "v": "09",
            "num": 9
          },
          {
            "kind": "machine",
            "v": "44",
            "num": 44
          },
          {
            "kind": "machine",
            "v": "86",
            "num": 86
          },
          {
            "kind": "machine",
            "v": "106",
            "num": 106
          },
          {
            "kind": "machine",
            "v": "37",
            "num": 37
          },
          {
            "kind": "machine",
            "v": "38",
            "num": 38
          },
          {
            "kind": "machine",
            "v": "74",
            "num": 74
          },
          {
            "kind": "line",
            "v": "LINE14"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "machine",
            "v": "27",
            "num": 27
          },
          {
            "kind": "machine",
            "v": "28",
            "num": 28
          },
          {
            "kind": "machine",
            "v": "29",
            "num": 29
          },
          {
            "kind": "machine",
            "v": "30",
            "num": 30
          },
          {
            "kind": "machine",
            "v": "31",
            "num": 31
          },
          {
            "kind": "machine",
            "v": "105",
            "num": 105
          },
          {
            "kind": "machine",
            "v": "52",
            "num": 52
          },
          {
            "kind": "machine",
            "v": "12",
            "num": 12
          },
          {
            "kind": "machine",
            "v": "54",
            "num": 54
          },
          {
            "kind": "machine",
            "v": "98",
            "num": 98
          },
          {
            "kind": "machine",
            "v": "100",
            "num": 100
          },
          {
            "kind": "machine",
            "v": "102",
            "num": 102
          },
          {
            "kind": "machine",
            "v": "39",
            "num": 39
          },
          {
            "kind": "machine",
            "v": "72",
            "num": 72
          },
          {
            "kind": "machine",
            "v": "42",
            "num": 42
          },
          {
            "kind": "machine",
            "v": "41",
            "num": 41
          },
          {
            "kind": "machine",
            "v": "43",
            "num": 43
          },
          {
            "kind": "machine",
            "v": "46",
            "num": 46
          },
          {
            "kind": "line",
            "v": "LINE27"
          },
          {
            "kind": "machine",
            "v": "202",
            "num": 202
          },
          {
            "kind": "machine",
            "v": "150",
            "num": 150
          },
          {
            "kind": "machine",
            "v": "162",
            "num": 162
          },
          {
            "kind": "machine",
            "v": "151",
            "num": 151
          },
          {
            "kind": "machine",
            "v": "167",
            "num": 167
          },
          {
            "kind": "machine",
            "v": "186",
            "num": 186
          },
          {
            "kind": "machine",
            "v": "185",
            "num": 185
          },
          {
            "kind": "machine",
            "v": "177",
            "num": 177
          },
          {
            "kind": "machine",
            "v": "152",
            "num": 152
          },
          {
            "kind": "machine",
            "v": "173",
            "num": 173
          },
          {
            "kind": "machine",
            "v": "154",
            "num": 154
          },
          {
            "kind": "machine",
            "v": "155",
            "num": 155
          },
          {
            "kind": "machine",
            "v": "188",
            "num": 188
          },
          {
            "kind": "machine",
            "v": "190",
            "num": 190
          },
          {
            "kind": "machine",
            "v": "191",
            "num": 191
          },
          {
            "kind": "machine",
            "v": "193",
            "num": 193
          },
          {
            "kind": "machine",
            "v": "194",
            "num": 194
          },
          {
            "kind": "machine",
            "v": "199",
            "num": 199
          },
          {
            "kind": "line",
            "v": "LINE13"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "machine",
            "v": "89",
            "num": 89
          },
          {
            "kind": "machine",
            "v": "35",
            "num": 35
          },
          {
            "kind": "machine",
            "v": "211",
            "num": 211
          },
          {
            "kind": "machine",
            "v": "260",
            "num": 260
          },
          {
            "kind": "machine",
            "v": "261",
            "num": 261
          },
          {
            "kind": "machine",
            "v": "262",
            "num": 262
          },
          {
            "kind": "machine",
            "v": "263",
            "num": 263
          },
          {
            "kind": "machine",
            "v": "264",
            "num": 264
          },
          {
            "kind": "machine",
            "v": "265",
            "num": 265
          },
          {
            "kind": "machine",
            "v": "266",
            "num": 266
          },
          {
            "kind": "machine",
            "v": "267",
            "num": 267
          },
          {
            "kind": "machine",
            "v": "268",
            "num": 268
          },
          {
            "kind": "machine",
            "v": "269",
            "num": 269
          },
          {
            "kind": "machine",
            "v": "270",
            "num": 270
          },
          {
            "kind": "machine",
            "v": "271",
            "num": 271
          },
          {
            "kind": "machine",
            "v": "272",
            "num": 272
          },
          {
            "kind": "machine",
            "v": "273",
            "num": 273
          },
          {
            "kind": "line",
            "v": "LINE26"
          },
          {
            "kind": "machine",
            "v": "175",
            "num": 175
          },
          {
            "kind": "machine",
            "v": "174",
            "num": 174
          },
          {
            "kind": "machine",
            "v": "172",
            "num": 172
          },
          {
            "kind": "machine",
            "v": "158",
            "num": 158
          },
          {
            "kind": "machine",
            "v": "156",
            "num": 156
          },
          {
            "kind": "machine",
            "v": "149",
            "num": 149
          },
          {
            "kind": "machine",
            "v": "138",
            "num": 138
          },
          {
            "kind": "machine",
            "v": "14",
            "num": 14
          },
          {
            "kind": "machine",
            "v": "164",
            "num": 164
          },
          {
            "kind": "machine",
            "v": "192",
            "num": 192
          },
          {
            "kind": "machine",
            "v": "178",
            "num": 178
          },
          {
            "kind": "machine",
            "v": "147",
            "num": 147
          },
          {
            "kind": "machine",
            "v": "140",
            "num": 140
          },
          {
            "kind": "machine",
            "v": "139",
            "num": 139
          },
          {
            "kind": "machine",
            "v": "136",
            "num": 136
          },
          {
            "kind": "machine",
            "v": "135",
            "num": 135
          },
          {
            "kind": "machine",
            "v": "133",
            "num": 133
          },
          {
            "kind": "machine",
            "v": "132",
            "num": 132
          },
          {
            "kind": "line",
            "v": "LINE12"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "machine",
            "v": "363",
            "num": 363
          },
          {
            "kind": "machine",
            "v": "352",
            "num": 352
          },
          {
            "kind": "machine",
            "v": "351",
            "num": 351
          },
          {
            "kind": "machine",
            "v": "350",
            "num": 350
          },
          {
            "kind": "machine",
            "v": "349",
            "num": 349
          },
          {
            "kind": "machine",
            "v": "342",
            "num": 342
          },
          {
            "kind": "machine",
            "v": "343",
            "num": 343
          },
          {
            "kind": "machine",
            "v": "344",
            "num": 344
          },
          {
            "kind": "machine",
            "v": "345",
            "num": 345
          },
          {
            "kind": "machine",
            "v": "346",
            "num": 346
          },
          {
            "kind": "machine",
            "v": "347",
            "num": 347
          },
          {
            "kind": "machine",
            "v": "348",
            "num": 348
          },
          {
            "kind": "line",
            "v": "LINE25"
          },
          {
            "kind": "machine",
            "v": "129",
            "num": 129
          },
          {
            "kind": "machine",
            "v": "130",
            "num": 130
          },
          {
            "kind": "machine",
            "v": "131",
            "num": 131
          },
          {
            "kind": "machine",
            "v": "203",
            "num": 203
          },
          {
            "kind": "machine",
            "v": "204",
            "num": 204
          },
          {
            "kind": "machine",
            "v": "134",
            "num": 134
          },
          {
            "kind": "machine",
            "v": "187",
            "num": 187
          },
          {
            "kind": "machine",
            "v": "201",
            "num": 201
          },
          {
            "kind": "machine",
            "v": "205",
            "num": 205
          },
          {
            "kind": "machine",
            "v": "128",
            "num": 128
          },
          {
            "kind": "machine",
            "v": "153",
            "num": 153
          },
          {
            "kind": "machine",
            "v": "148",
            "num": 148
          },
          {
            "kind": "machine",
            "v": "64",
            "num": 64
          },
          {
            "kind": "machine",
            "v": "109",
            "num": 109
          },
          {
            "kind": "machine",
            "v": "108",
            "num": 108
          },
          {
            "kind": "machine",
            "v": "107",
            "num": 107
          },
          {
            "kind": "machine",
            "v": "103",
            "num": 103
          },
          {
            "kind": "machine",
            "v": "111",
            "num": 111
          },
          {
            "kind": "line",
            "v": "LINE11"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "machine",
            "v": "377",
            "num": 377
          },
          {
            "kind": "machine",
            "v": "376",
            "num": 376
          },
          {
            "kind": "machine",
            "v": "375",
            "num": 375
          },
          {
            "kind": "machine",
            "v": "374",
            "num": 374
          },
          {
            "kind": "machine",
            "v": "373",
            "num": 373
          },
          {
            "kind": "machine",
            "v": "372",
            "num": 372
          },
          {
            "kind": "machine",
            "v": "371",
            "num": 371
          },
          {
            "kind": "machine",
            "v": "370",
            "num": 370
          },
          {
            "kind": "machine",
            "v": "369",
            "num": 369
          },
          {
            "kind": "machine",
            "v": "368",
            "num": 368
          },
          {
            "kind": "machine",
            "v": "367",
            "num": 367
          },
          {
            "kind": "machine",
            "v": "366",
            "num": 366
          },
          {
            "kind": "line",
            "v": "LINE24"
          },
          {
            "kind": "machine",
            "v": "87",
            "num": 87
          },
          {
            "kind": "machine",
            "v": "07",
            "num": 7
          },
          {
            "kind": "machine",
            "v": "84",
            "num": 84
          },
          {
            "kind": "machine",
            "v": "101",
            "num": 101
          },
          {
            "kind": "machine",
            "v": "519",
            "num": 519
          },
          {
            "kind": "machine",
            "v": "518",
            "num": 518
          },
          {
            "kind": "machine",
            "v": "517",
            "num": 517
          },
          {
            "kind": "machine",
            "v": "516",
            "num": 516
          },
          {
            "kind": "machine",
            "v": "515",
            "num": 515
          },
          {
            "kind": "machine",
            "v": "514",
            "num": 514
          },
          {
            "kind": "machine",
            "v": "513",
            "num": 513
          },
          {
            "kind": "machine",
            "v": "512",
            "num": 512
          },
          {
            "kind": "machine",
            "v": "511",
            "num": 511
          },
          {
            "kind": "machine",
            "v": "510",
            "num": 510
          },
          {
            "kind": "machine",
            "v": "509",
            "num": 509
          },
          {
            "kind": "machine",
            "v": "508",
            "num": 508
          },
          {
            "kind": "line",
            "v": "LINE10"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "machine",
            "v": "365",
            "num": 365
          },
          {
            "kind": "machine",
            "v": "364",
            "num": 364
          },
          {
            "kind": "machine",
            "v": "358",
            "num": 358
          },
          {
            "kind": "machine",
            "v": "357",
            "num": 357
          },
          {
            "kind": "machine",
            "v": "356",
            "num": 356
          },
          {
            "kind": "machine",
            "v": "355",
            "num": 355
          },
          {
            "kind": "machine",
            "v": "354",
            "num": 354
          },
          {
            "kind": "machine",
            "v": "353",
            "num": 353
          },
          {
            "kind": "machine",
            "v": "359",
            "num": 359
          },
          {
            "kind": "machine",
            "v": "360",
            "num": 360
          },
          {
            "kind": "machine",
            "v": "361",
            "num": 361
          },
          {
            "kind": "machine",
            "v": "362",
            "num": 362
          },
          {
            "kind": "line",
            "v": "LINE23"
          },
          {
            "kind": "support",
            "v": "WIRE CARBINET",
            "color": "#FFCCFF"
          },
          {
            "kind": "machine",
            "v": "406",
            "num": 406
          },
          {
            "kind": "machine",
            "v": "405",
            "num": 405
          },
          {
            "kind": "machine",
            "v": "404",
            "num": 404
          },
          {
            "kind": "machine",
            "v": "403",
            "num": 403
          },
          {
            "kind": "machine",
            "v": "402",
            "num": 402
          },
          {
            "kind": "machine",
            "v": "401",
            "num": 401
          },
          {
            "kind": "machine",
            "v": "394",
            "num": 394
          },
          {
            "kind": "machine",
            "v": "393",
            "num": 393
          },
          {
            "kind": "machine",
            "v": "392",
            "num": 392
          },
          {
            "kind": "machine",
            "v": "391",
            "num": 391
          },
          {
            "kind": "machine",
            "v": "390",
            "num": 390
          },
          {
            "kind": "machine",
            "v": "389",
            "num": 389
          },
          {
            "kind": "line",
            "v": "LINE09"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "machine",
            "v": "329",
            "num": 329
          },
          {
            "kind": "machine",
            "v": "407",
            "num": 407
          },
          {
            "kind": "machine",
            "v": "49",
            "num": 49
          },
          {
            "kind": "machine",
            "v": "48",
            "num": 48
          },
          {
            "kind": "machine",
            "v": "47",
            "num": 47
          },
          {
            "kind": "support",
            "v": "ISP23",
            "color": "#9FE0B0"
          },
          {
            "kind": "support",
            "v": "IS18",
            "color": "#9FE0B0"
          },
          {
            "kind": "support",
            "v": "ISP09",
            "color": "#9FE0B0"
          },
          {
            "kind": "support",
            "v": "QC CENTER",
            "color": "#FFCCFF"
          },
          {
            "kind": "line",
            "v": "LINE22"
          },
          {
            "kind": "support",
            "v": "SUP1",
            "color": "#00FF99"
          },
          {
            "kind": "support",
            "v": "ISP01",
            "color": "#9FE0B0"
          },
          {
            "kind": "machine",
            "v": "398",
            "num": 398
          },
          {
            "kind": "machine",
            "v": "397",
            "num": 397
          },
          {
            "kind": "machine",
            "v": "396",
            "num": 396
          },
          {
            "kind": "machine",
            "v": "395",
            "num": 395
          },
          {
            "kind": "machine",
            "v": "388",
            "num": 388
          },
          {
            "kind": "machine",
            "v": "387",
            "num": 387
          },
          {
            "kind": "machine",
            "v": "386",
            "num": 386
          },
          {
            "kind": "machine",
            "v": "385",
            "num": 385
          },
          {
            "kind": "machine",
            "v": "400",
            "num": 400
          },
          {
            "kind": "machine",
            "v": "399",
            "num": 399
          },
          {
            "kind": "line",
            "v": "LINE08"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "support",
            "v": "PLASMA01",
            "color": "#C8E6A0"
          },
          {
            "kind": "support",
            "v": "PLASMA02",
            "color": "#C8E6A0"
          },
          {
            "kind": "support",
            "v": "PLASMA03",
            "color": "#C8E6A0"
          },
          {
            "kind": "support",
            "v": "QC CENTER",
            "color": "#FFCCFF"
          },
          {
            "kind": "line",
            "v": "LINE21"
          },
          {
            "kind": "support",
            "v": "SUP2",
            "color": "#00FF99"
          },
          {
            "kind": "machine",
            "v": "110",
            "num": 110
          },
          {
            "kind": "machine",
            "v": "58",
            "num": 58
          },
          {
            "kind": "machine",
            "v": "99",
            "num": 99
          },
          {
            "kind": "machine",
            "v": "1",
            "num": 1
          },
          {
            "kind": "machine",
            "v": "77",
            "num": 77
          },
          {
            "kind": "machine",
            "v": "66",
            "num": 66
          },
          {
            "kind": "machine",
            "v": "76",
            "num": 76
          },
          {
            "kind": "support",
            "v": "SUPQC",
            "color": "#00FF99"
          },
          {
            "kind": "line",
            "v": "LINE07"
          }
        ]
      }
    ]
  },
  {
    "id": "Z2",
    "label": "ZONE 2 (TQFP)",
    "supervisor": "โบว์ , รุ้ง",
    "rows": [
      {
        "cells": [
          {
            "kind": "machine",
            "v": "237",
            "num": 237
          },
          {
            "kind": "machine",
            "v": "236",
            "num": 236
          },
          {
            "kind": "machine",
            "v": "207",
            "num": 207
          },
          {
            "kind": "machine",
            "v": "208",
            "num": 208
          },
          {
            "kind": "machine",
            "v": "247",
            "num": 247
          },
          {
            "kind": "machine",
            "v": "253",
            "num": 253
          },
          {
            "kind": "machine",
            "v": "240",
            "num": 240
          },
          {
            "kind": "machine",
            "v": "249",
            "num": 249
          },
          {
            "kind": "machine",
            "v": "250",
            "num": 250
          },
          {
            "kind": "machine",
            "v": "251",
            "num": 251
          },
          {
            "kind": "machine",
            "v": "254",
            "num": 254
          },
          {
            "kind": "machine",
            "v": "239",
            "num": 239
          },
          {
            "kind": "line",
            "v": "LINE20"
          },
          {
            "kind": "machine",
            "v": "255",
            "num": 255
          },
          {
            "kind": "machine",
            "v": "209",
            "num": 209
          },
          {
            "kind": "machine",
            "v": "210",
            "num": 210
          },
          {
            "kind": "machine",
            "v": "212",
            "num": 212
          },
          {
            "kind": "machine",
            "v": "213",
            "num": 213
          },
          {
            "kind": "machine",
            "v": "248",
            "num": 248
          },
          {
            "kind": "machine",
            "v": "230",
            "num": 230
          },
          {
            "kind": "machine",
            "v": "231",
            "num": 231
          },
          {
            "kind": "machine",
            "v": "232",
            "num": 232
          },
          {
            "kind": "machine",
            "v": "233",
            "num": 233
          },
          {
            "kind": "machine",
            "v": "234",
            "num": 234
          },
          {
            "kind": "machine",
            "v": "235",
            "num": 235
          },
          {
            "kind": "line",
            "v": "LINE06"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "machine",
            "v": "215",
            "num": 215
          },
          {
            "kind": "machine",
            "v": "216",
            "num": 216
          },
          {
            "kind": "machine",
            "v": "217",
            "num": 217
          },
          {
            "kind": "machine",
            "v": "223",
            "num": 223
          },
          {
            "kind": "machine",
            "v": "224",
            "num": 224
          },
          {
            "kind": "machine",
            "v": "225",
            "num": 225
          },
          {
            "kind": "machine",
            "v": "226",
            "num": 226
          },
          {
            "kind": "machine",
            "v": "227",
            "num": 227
          },
          {
            "kind": "machine",
            "v": "228",
            "num": 228
          },
          {
            "kind": "machine",
            "v": "229",
            "num": 229
          },
          {
            "kind": "machine",
            "v": "184",
            "num": 184
          },
          {
            "kind": "machine",
            "v": "241",
            "num": 241
          },
          {
            "kind": "line",
            "v": "LINE19"
          },
          {
            "kind": "machine",
            "v": "242",
            "num": 242
          },
          {
            "kind": "machine",
            "v": "218",
            "num": 218
          },
          {
            "kind": "machine",
            "v": "219",
            "num": 219
          },
          {
            "kind": "machine",
            "v": "220",
            "num": 220
          },
          {
            "kind": "machine",
            "v": "221",
            "num": 221
          },
          {
            "kind": "machine",
            "v": "222",
            "num": 222
          },
          {
            "kind": "machine",
            "v": "246",
            "num": 246
          },
          {
            "kind": "machine",
            "v": "258",
            "num": 258
          },
          {
            "kind": "machine",
            "v": "243",
            "num": 243
          },
          {
            "kind": "machine",
            "v": "244",
            "num": 244
          },
          {
            "kind": "machine",
            "v": "245",
            "num": 245
          },
          {
            "kind": "machine",
            "v": "252",
            "num": 252
          },
          {
            "kind": "line",
            "v": "LINE05"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "machine",
            "v": "311",
            "num": 311
          },
          {
            "kind": "machine",
            "v": "312",
            "num": 312
          },
          {
            "kind": "machine",
            "v": "315",
            "num": 315
          },
          {
            "kind": "machine",
            "v": "316",
            "num": 316
          },
          {
            "kind": "machine",
            "v": "317",
            "num": 317
          },
          {
            "kind": "machine",
            "v": "318",
            "num": 318
          },
          {
            "kind": "machine",
            "v": "290",
            "num": 290
          },
          {
            "kind": "machine",
            "v": "291",
            "num": 291
          },
          {
            "kind": "machine",
            "v": "292",
            "num": 292
          },
          {
            "kind": "machine",
            "v": "259",
            "num": 259
          },
          {
            "kind": "machine",
            "v": "214",
            "num": 214
          },
          {
            "kind": "machine",
            "v": "320",
            "num": 320
          },
          {
            "kind": "line",
            "v": "LINE18"
          },
          {
            "kind": "machine",
            "v": "314",
            "num": 314
          },
          {
            "kind": "machine",
            "v": "313",
            "num": 313
          },
          {
            "kind": "machine",
            "v": "303",
            "num": 303
          },
          {
            "kind": "machine",
            "v": "321",
            "num": 321
          },
          {
            "kind": "machine",
            "v": "322",
            "num": 322
          },
          {
            "kind": "machine",
            "v": "323",
            "num": 323
          },
          {
            "kind": "machine",
            "v": "324",
            "num": 324
          },
          {
            "kind": "machine",
            "v": "325",
            "num": 325
          },
          {
            "kind": "machine",
            "v": "378",
            "num": 378
          },
          {
            "kind": "machine",
            "v": "282",
            "num": 282
          },
          {
            "kind": "machine",
            "v": "327",
            "num": 327
          },
          {
            "kind": "machine",
            "v": "328",
            "num": 328
          },
          {
            "kind": "line",
            "v": "LINE04"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "machine",
            "v": "304",
            "num": 304
          },
          {
            "kind": "machine",
            "v": "307",
            "num": 307
          },
          {
            "kind": "machine",
            "v": "308",
            "num": 308
          },
          {
            "kind": "machine",
            "v": "309",
            "num": 309
          },
          {
            "kind": "machine",
            "v": "310",
            "num": 310
          },
          {
            "kind": "machine",
            "v": "275",
            "num": 275
          },
          {
            "kind": "machine",
            "v": "289",
            "num": 289
          },
          {
            "kind": "machine",
            "v": "288",
            "num": 288
          },
          {
            "kind": "machine",
            "v": "287",
            "num": 287
          },
          {
            "kind": "machine",
            "v": "330",
            "num": 330
          },
          {
            "kind": "machine",
            "v": "331",
            "num": 331
          },
          {
            "kind": "machine",
            "v": "332",
            "num": 332
          },
          {
            "kind": "line",
            "v": "LINE17"
          },
          {
            "kind": "machine",
            "v": "306",
            "num": 306
          },
          {
            "kind": "machine",
            "v": "379",
            "num": 379
          },
          {
            "kind": "machine",
            "v": "276",
            "num": 276
          },
          {
            "kind": "machine",
            "v": "277",
            "num": 277
          },
          {
            "kind": "machine",
            "v": "286",
            "num": 286
          },
          {
            "kind": "machine",
            "v": "285",
            "num": 285
          },
          {
            "kind": "machine",
            "v": "278",
            "num": 278
          },
          {
            "kind": "machine",
            "v": "279",
            "num": 279
          },
          {
            "kind": "machine",
            "v": "280",
            "num": 280
          },
          {
            "kind": "machine",
            "v": "281",
            "num": 281
          },
          {
            "kind": "machine",
            "v": "283",
            "num": 283
          },
          {
            "kind": "machine",
            "v": "284",
            "num": 284
          },
          {
            "kind": "line",
            "v": "LINE03"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "machine",
            "v": "333",
            "num": 333
          },
          {
            "kind": "machine",
            "v": "334",
            "num": 334
          },
          {
            "kind": "machine",
            "v": "335",
            "num": 335
          },
          {
            "kind": "machine",
            "v": "336",
            "num": 336
          },
          {
            "kind": "machine",
            "v": "337",
            "num": 337
          },
          {
            "kind": "machine",
            "v": "338",
            "num": 338
          },
          {
            "kind": "machine",
            "v": "339",
            "num": 339
          },
          {
            "kind": "machine",
            "v": "340",
            "num": 340
          },
          {
            "kind": "machine",
            "v": "341",
            "num": 341
          },
          {
            "kind": "machine",
            "v": "382",
            "num": 382
          },
          {
            "kind": "machine",
            "v": "381",
            "num": 381
          },
          {
            "kind": "machine",
            "v": "380",
            "num": 380
          },
          {
            "kind": "line",
            "v": "LINE16"
          },
          {
            "kind": "machine",
            "v": "319",
            "num": 319
          },
          {
            "kind": "machine",
            "v": "293",
            "num": 293
          },
          {
            "kind": "machine",
            "v": "297",
            "num": 297
          },
          {
            "kind": "machine",
            "v": "298",
            "num": 298
          },
          {
            "kind": "machine",
            "v": "299",
            "num": 299
          },
          {
            "kind": "machine",
            "v": "300",
            "num": 300
          },
          {
            "kind": "machine",
            "v": "301",
            "num": 301
          },
          {
            "kind": "machine",
            "v": "302",
            "num": 302
          },
          {
            "kind": "machine",
            "v": "305",
            "num": 305
          },
          {
            "kind": "machine",
            "v": "295",
            "num": 295
          },
          {
            "kind": "machine",
            "v": "294",
            "num": 294
          },
          {
            "kind": "machine",
            "v": "296",
            "num": 296
          },
          {
            "kind": "line",
            "v": "LINE02"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "machine",
            "v": "418",
            "num": 418
          },
          {
            "kind": "machine",
            "v": "419",
            "num": 419
          },
          {
            "kind": "machine",
            "v": "420",
            "num": 420
          },
          {
            "kind": "machine",
            "v": "421",
            "num": 421
          },
          {
            "kind": "machine",
            "v": "422",
            "num": 422
          },
          {
            "kind": "machine",
            "v": "423",
            "num": 423
          },
          {
            "kind": "machine",
            "v": "424",
            "num": 424
          },
          {
            "kind": "machine",
            "v": "425",
            "num": 425
          },
          {
            "kind": "machine",
            "v": "426",
            "num": 426
          },
          {
            "kind": "machine",
            "v": "427",
            "num": 427
          },
          {
            "kind": "machine",
            "v": "428",
            "num": 428
          },
          {
            "kind": "line",
            "v": "LINE15"
          },
          {
            "kind": "machine",
            "v": "433",
            "num": 433
          },
          {
            "kind": "machine",
            "v": "429",
            "num": 429
          },
          {
            "kind": "machine",
            "v": "430",
            "num": 430
          },
          {
            "kind": "machine",
            "v": "431",
            "num": 431
          },
          {
            "kind": "machine",
            "v": "432",
            "num": 432
          },
          {
            "kind": "machine",
            "v": "507",
            "num": 507
          },
          {
            "kind": "machine",
            "v": "506",
            "num": 506
          },
          {
            "kind": "machine",
            "v": "505",
            "num": 505
          },
          {
            "kind": "machine",
            "v": "504",
            "num": 504
          },
          {
            "kind": "machine",
            "v": "503",
            "num": 503
          },
          {
            "kind": "machine",
            "v": "502",
            "num": 502
          },
          {
            "kind": "line",
            "v": "LINE01"
          }
        ]
      }
    ]
  },
  {
    "id": "Z3",
    "label": "ZONE 3 (QFN Old Room)",
    "supervisor": "สุ , น้อย",
    "rows": [
      {
        "cells": [
          {
            "kind": "machine",
            "v": "417",
            "num": 417
          },
          {
            "kind": "machine",
            "v": "416",
            "num": 416
          },
          {
            "kind": "machine",
            "v": "415",
            "num": 415
          },
          {
            "kind": "machine",
            "v": "414",
            "num": 414
          },
          {
            "kind": "machine",
            "v": "413",
            "num": 413
          },
          {
            "kind": "machine",
            "v": "412",
            "num": 412
          },
          {
            "kind": "machine",
            "v": "411",
            "num": 411
          },
          {
            "kind": "machine",
            "v": "410",
            "num": 410
          },
          {
            "kind": "machine",
            "v": "409",
            "num": 409
          },
          {
            "kind": "machine",
            "v": "408",
            "num": 408
          },
          {
            "kind": "line",
            "v": "LINE9"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "support",
            "v": "3/O+QC Die Attacn",
            "color": "#FFCCFF"
          },
          {
            "kind": "machine",
            "v": "501",
            "num": 501
          },
          {
            "kind": "machine",
            "v": "500",
            "num": 500
          },
          {
            "kind": "machine",
            "v": "499",
            "num": 499
          },
          {
            "kind": "machine",
            "v": "498",
            "num": 498
          },
          {
            "kind": "line",
            "v": "LINE8"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "support",
            "v": "SUPV 3",
            "color": "#00FF99"
          },
          {
            "kind": "support",
            "v": "QC Wire bond",
            "color": "#FFCCFF"
          },
          {
            "kind": "machine",
            "v": "497",
            "num": 497
          },
          {
            "kind": "machine",
            "v": "496",
            "num": 496
          },
          {
            "kind": "machine",
            "v": "495",
            "num": 495
          },
          {
            "kind": "machine",
            "v": "494",
            "num": 494
          },
          {
            "kind": "line",
            "v": "LINE7"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "machine",
            "v": "493",
            "num": 493
          },
          {
            "kind": "machine",
            "v": "492",
            "num": 492
          },
          {
            "kind": "machine",
            "v": "491",
            "num": 491
          },
          {
            "kind": "machine",
            "v": "490",
            "num": 490
          },
          {
            "kind": "machine",
            "v": "489",
            "num": 489
          },
          {
            "kind": "machine",
            "v": "488",
            "num": 488
          },
          {
            "kind": "machine",
            "v": "487",
            "num": 487
          },
          {
            "kind": "machine",
            "v": "486",
            "num": 486
          },
          {
            "kind": "machine",
            "v": "485",
            "num": 485
          },
          {
            "kind": "machine",
            "v": "484",
            "num": 484
          },
          {
            "kind": "line",
            "v": "LINE6"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "support",
            "v": "MOLD  LINE",
            "color": "#A8C0E0"
          },
          {
            "kind": "machine",
            "v": "483",
            "num": 483
          },
          {
            "kind": "machine",
            "v": "482",
            "num": 482
          },
          {
            "kind": "machine",
            "v": "481",
            "num": 481
          },
          {
            "kind": "machine",
            "v": "480",
            "num": 480
          },
          {
            "kind": "machine",
            "v": "479",
            "num": 479
          },
          {
            "kind": "machine",
            "v": "478",
            "num": 478
          },
          {
            "kind": "machine",
            "v": "477",
            "num": 477
          },
          {
            "kind": "machine",
            "v": "476",
            "num": 476
          },
          {
            "kind": "machine",
            "v": "475",
            "num": 475
          },
          {
            "kind": "machine",
            "v": "474",
            "num": 474
          },
          {
            "kind": "line",
            "v": "LINE5"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "machine",
            "v": "473",
            "num": 473
          },
          {
            "kind": "machine",
            "v": "472",
            "num": 472
          },
          {
            "kind": "machine",
            "v": "471",
            "num": 471
          },
          {
            "kind": "machine",
            "v": "470",
            "num": 470
          },
          {
            "kind": "machine",
            "v": "469",
            "num": 469
          },
          {
            "kind": "machine",
            "v": "468",
            "num": 468
          },
          {
            "kind": "machine",
            "v": "467",
            "num": 467
          },
          {
            "kind": "machine",
            "v": "466",
            "num": 466
          },
          {
            "kind": "machine",
            "v": "465",
            "num": 465
          },
          {
            "kind": "machine",
            "v": "464",
            "num": 464
          },
          {
            "kind": "line",
            "v": "LINE4"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "machine",
            "v": "463",
            "num": 463
          },
          {
            "kind": "machine",
            "v": "462",
            "num": 462
          },
          {
            "kind": "machine",
            "v": "461",
            "num": 461
          },
          {
            "kind": "machine",
            "v": "460",
            "num": 460
          },
          {
            "kind": "machine",
            "v": "459",
            "num": 459
          },
          {
            "kind": "machine",
            "v": "458",
            "num": 458
          },
          {
            "kind": "machine",
            "v": "457",
            "num": 457
          },
          {
            "kind": "machine",
            "v": "456",
            "num": 456
          },
          {
            "kind": "machine",
            "v": "455",
            "num": 455
          },
          {
            "kind": "machine",
            "v": "454",
            "num": 454
          },
          {
            "kind": "line",
            "v": "LINE3"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "machine",
            "v": "453",
            "num": 453
          },
          {
            "kind": "machine",
            "v": "452",
            "num": 452
          },
          {
            "kind": "machine",
            "v": "451",
            "num": 451
          },
          {
            "kind": "machine",
            "v": "450",
            "num": 450
          },
          {
            "kind": "machine",
            "v": "449",
            "num": 449
          },
          {
            "kind": "machine",
            "v": "448",
            "num": 448
          },
          {
            "kind": "machine",
            "v": "447",
            "num": 447
          },
          {
            "kind": "machine",
            "v": "446",
            "num": 446
          },
          {
            "kind": "machine",
            "v": "445",
            "num": 445
          },
          {
            "kind": "machine",
            "v": "444",
            "num": 444
          },
          {
            "kind": "line",
            "v": "LINE2"
          }
        ]
      },
      {
        "cells": [
          {
            "kind": "machine",
            "v": "443",
            "num": 443
          },
          {
            "kind": "machine",
            "v": "442",
            "num": 442
          },
          {
            "kind": "machine",
            "v": "441",
            "num": 441
          },
          {
            "kind": "machine",
            "v": "440",
            "num": 440
          },
          {
            "kind": "machine",
            "v": "439",
            "num": 439
          },
          {
            "kind": "machine",
            "v": "438",
            "num": 438
          },
          {
            "kind": "machine",
            "v": "437",
            "num": 437
          },
          {
            "kind": "machine",
            "v": "436",
            "num": 436
          },
          {
            "kind": "machine",
            "v": "435",
            "num": 435
          },
          {
            "kind": "machine",
            "v": "434",
            "num": 434
          },
          {
            "kind": "line",
            "v": "LINE1"
          }
        ]
      }
    ]
  }
];
